import pandas as pd
from fpdf import FPDF

# Load student data from csv
df = pd.read_csv('students.csv')

# Analysis average marks per student
summary = df.groupby('Name')['Marks'].agg(['count', 'mean', 'min', 'max']).reset_index()
summary.columns = ['Student Name', 'Subjects Taken', 'Average Marks', 'Min Marks', 'Max Marks']

# Create PDF 
class StudentPDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, 'Student Performance Report', ln=True, align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

    def add_summary_table(self, summary_df):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Summary of Student Marks:', ln=True)
        self.ln(5)

        self.set_font('Arial', 'B', 10)
        col_widths = [50, 40, 35, 30, 30]
        headers = summary_df.columns.tolist()
        for i, header in enumerate(headers):
            self.cell(col_widths[i], 8, header, border=1)
        self.ln()

        self.set_font('Arial', '', 10)
        for index, row in summary_df.iterrows():
            for i, item in enumerate(row):
                self.cell(col_widths[i], 8, str(round(item, 2)) if isinstance(item, float) else str(item), border=1)
            self.ln()

# Generate PDF from the csv file
pdf = StudentPDFReport()
pdf.add_page()
pdf.add_summary_table(summary)
pdf.output("student_performance_report.pdf")

print("PDF report generated by MAYUR : student_performance_report.pdf")
